### ISSUE TITLE
Update to Stylelint 14 and the latest plugin versions

### ISSUE THREAD

**Issue by XhmikosR** [twbs/stylelint-config-twbs-bootstrap#128]
@jeddy3: if you have any free time, I'd appreciate if you could help us here move forward :)

This might be a good chance to fix #123 too, but not strictly necessary.

**Comment by fgblomqvist** [comment]
Do you guys need help here? Shouldn't updating the versions be a very simple/quick task? The overrides stuff should happen in a separate issue/PR to keep things moving imo.

**Comment by XhmikosR** [comment]
Yeah, we could definitely use help here! I have a branch which just updates the deps https://github.com/twbs/stylelint-config-twbs-bootstrap/compare/dev

But we need to update the packages to the new versions and it seems @jeddy has pinpointed another issue upstream.

Ideally we should make v3.0.0 with @jeddy3's suggestions since it looks like we could get many of our overrides.

**Comment by jeddy3** [comment]
> Shouldn't updating the versions be a very simple/quick task?

There are a [number of breaking changes in Stylelint 14](https://stylelint.io/migration-guide/to-14) and I think more may be needed than bumping the deps.

> and it seems @Jeddy has pinpointed another issue upstream.

The issue has been fixed in `main` and we hope to put out a release this weekend.

@fgblomqvist It'd be amazing if you could do the legwork of discovering which of the existing rules are still needed (considering that the major releases of the extended configs turn on a dozen new rules each). You can either use `main` of Stylelint as a temp dep or wait until 14.1.0 is out before opening a pull request, which I'm happy to look over. Just at-mention me as I don't watch this repo.

**Comment by fgblomqvist** [comment]
Sounds good, I'll see what I can accomplish this week

**Comment by jeddy3** [comment]
Thanks. `14.1.0` was released, so the following should work now:

```json
{
  "extends": ["stylelint-config-standard"],
  "plugins": ["stylelint-order"],
  "rules": {
    "color-named": "never",
    "font-weight-notation": [
      "numeric",
      {
        "ignore": ["relative"]
      }
    ],
    "order/properties-order": ["position" ..]
    ..
  },
  "overrides": [
    {
      "files": "**/*.scss",
      "extends": ["stylelint-config-standard-scss"],
      "rules": {
        ..
      }
    }
  ]
}
```
